services:
  api:
    build: .
    ports:
      - "8000:8000"
    # depends_on:
    #   - db
    env_file:
      - .env

  # db:
  #   image: postgres:17
  #   container_name: postgres-container
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: fastapi_db
  #   ports:
  #     - "5432:5432"